name: Daily Commit

on:
  schedule:
    - cron: '10 21 * * *'

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: sailesh.g@gramener.com
        run: |
          echo "This is a daily commit added by the GitHub Action" >> daily_commit.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "sailesh.g@gramener.com"
          git add daily_commit.txt
          git commit -m "Daily commit from GitHub Action"
          git push
