name: Daily Commit

on:
  schedule:
    # Run daily at 9:00 AM UTC
    - cron: '0 9 * * *'

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit with sailesh.g@gramener.com
        run: |
          echo "This is a daily commit added by the GitHub Action" >> daily_commit.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "sailesh.g@gramener.com"
          git add daily_commit.txt
          git commit -m "Daily commit from GitHub Action"
          git push
